# Generated by Django 3.2 on 2021-05-04 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tempfile',
            old_name='file',
            new_name='file_src',
        ),
    ]
